[package]
name = "shavee_pam"
authors = ["Ashutosh Verma <shavee@ashu.io>"]
version = "0.1.0"
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib"]
name = "shavee_pam"

[dependencies]
pamsm = {version="0.5.0", features=["libpam"] }
shavee_lib = {path = "../shavee-lib"}
clap = "2.33.3"
base64 = "0.13.0"

