[package]
name = "shavee-pam"
authors = ["Ashutosh Verma <shavee@ashu.io>"]
version = "0.1.0"
edition = "2018"
license = "MIT"

[lib]
name = "pam_shavee"
crate-type = ["cdylib"]

[dependencies]
pamsm = {version="0.5.0", features=["libpam"] }



