[package]
name = "shavee_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

yubico_manager = "0.8.2"
sha2 = "0.9.5"
curl = "0.4.38"
pbkdf2 = "0.8.0"