[package]
name = "shavee_core"
version = "0.5.2"
edition = "2018"

[dependencies]
yubico_manager = "0.9.0"
sha2 = "0.10.6"
curl = "0.4.44"
rust-argon2 = "1.0.0"
base64 = "0.21.0"
clap = { version = "3" , features = ["cargo"] }

[dev-dependencies]
tempfile = "*"
nix = "0"
random-string = "1"
