[package]
name = "shavee_core"
version = "0.5.0"
edition = "2018"


[dependencies]

yubico_manager = "0.9.0"
sha2 = "0.10.1"
curl = "0.4.38"
rust-argon2 = "1.0.0"
base64 = "0.13.0"
clap = { version = "3" , features = ["cargo"] }

[dev-dependencies]
tempfile = "*"
nix = "0.*"
random-string = "1"
