[package]
name = "shavee_core"
version = "0.1.0"
edition = "2018"


[dependencies]

yubico_manager = "0.9.0"
sha2 = "0.9.5"
curl = "0.4.38"
rust-argon2 = "0.8.3"
base64 = "0.13.0"
clap = "2.33.3"

[dev-dependencies]
tempfile = "*"
