[package]
name = "shavee"
version = "0.5.1"
authors = ["Ashutosh Verma <shavee@ashu.io>"]
edition = "2018"
license = "MIT"
description = "shavee is a program to automatically decrypt and mount ZFS datasets using Yubikey HMAC as 2FA or any USB drive with support for PAM to auto mount home directories."
homepage = "https://shavee.ashu.io"
documentation = "https://shavee.ashu.io"
readme = "README.md"
repository = "https://github.com/ashuio/shavee"

[features]
default = ["file", "yubikey"]
yubikey = []
file = []

[dependencies]
sha2 = "0.10.1"
clap = { version = "3", features = ["cargo"] }
rpassword = "5.0.1"
base64 = "0.13.0"
shavee_core = {path = "../shavee-core"}

[dev-dependencies]
stdio-override = "0"
tempfile = "*"
nix = "0"
random-string = "1"
